config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  
 get '/login' => 'sessions#new'
 post '/login' => 'sessions#create'
 delete '/logout' => 'sessions#destroy'

 get "/auth/:provider/callback" => 'sessions#google_auth'
 #get "/auth/google_oauth2/callback", to: "sessions#google_oauth"

 #get "/letter", to: "poems#letter"
 get "/search", to: "poems#search"
 
  resources :comments
  resources :poems do
    resources :comments 
  end
  resources :users 
  resources :poems 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :poem

  validates :content, presence: true
end

app/models/poem.rb
class Poem < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  validates :content, :title, presence: true

  scope :alphabetical, -> { order(:title) }

  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :poems
    has_many :comments, dependent: :destroy
    has_many :commented_poems, through: :comments, source: :poem

    has_secure_password
    
    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    private
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) 
    end

    def logged_in?
        !!current_user
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
  before_action :redirect_if_not_logged_in
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_authorised, only: [:edit, :update, :destroy]

  def index
    if params[:poem_id] && @poem = Poem.find_by(id: params[:poem_id])
        @comments = @poem.comments
    else
      
      @comments = Comment.all
    end
  end

  def new
    
    if params[:poem_id] && @poem = Poem.find_by(id: params[:poem_id])
      @comment = @poem.comments.build
    else
      
      @comment = Comment.new(poem_id: params[:poem_id])
    end
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      
      redirect_to comment_path(@comment)
      
    else
      @poem = Poem.find_by(id: params[:poem_id]) 
      render :new
    end
  end


  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def edit
    if params[:poem_id] && @poem = Poem.find_by(id: params[:poem_id])
      if @poem.nil?
          flash[:alert] = "Poem doesn't exist!"
        redirect_to poems_path
      else
    
        @comment = @poem.comments.find_by(id: params[:id])
      end
      else
        @comment = Comment.find_by(id: params[:id])
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to comment_path(@comment)
    else
      render :edit
    end
  end
  
  def destroy
    @poem = Poem.find_by(id: params[:poem_id])
    @comment.destroy
    redirect_to poem_comments_path(@poem)
    end
  private

  def comment_params
    params.require(:comment).permit(:content,:poem_id)
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id])
    if !@comment
      flash[:alert] = "Comment was not found"
      redirect_to comments_path
    end
  end

  def redirect_if_not_authorised
      redirect_to comments_path if @comment.user != current_user
  end
        

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_poem, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_authorised, only: [:edit, :update]
   
  #poems_path
    def index
      @poems = Poem.all.alphabetical
      
    end

    def new
          @poem = Poem.new
    end

    def create
        @poem = current_user.poems.build(poem_params)
        if @poem.save
          redirect_to poems_path
        else
          render :new
        end
    end

    def show
    
      redirect_to poems_path if !@poem
    end

    def edit
     # @poem = Poem.find_by(id: params[:id])
      #redirect_to poems_path if !@poem || @poem.user != current_user
    end
    
    def update
     
     if @poem.update(poem_params)
       redirect_to poem_path(@poem)
     else
       render :edit
     end
   end

   def destroy
   
    @poem.destroy
    redirect_to poems_path
   end
  
   def search
      if params[:letter].blank? 

        redirect_to poems_path
      
      else
        @poems = Poem.all
        @letter = params[:letter].upcase
        @results = @poems.all.select{|poem|poem.title[0] == @letter} 
      end
   end
    
    private
      def poem_params
        params.require(:poem).permit(:title,:content)
      end

      def set_poem
        @poem = Poem.find_by(id: params[:id])
      end

      def redirect_if_not_authorised
        
        redirect_to poems_path if !@poem || @poem.user != current_user
     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def home
    end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          flash[:notice] = "Sucessfully logged in!"
          redirect_to user_path(@user)
        else
          flash[:alert] = "Invalid credentials, please try again"
          redirect_to "/login"
        end
      end
     
      def google_auth
       
        @user = User.find_or_create_by(email: auth['info']['email']) do |u|
          u.name = auth['info']['name']
          u.password = SecureRandom.hex
        end
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
          
        else
          redirect_to '/'
        end
      end


      def destroy
        session.clear
        redirect_to root_path
      end

      private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "You have sucessfully created an account, #{@user.name}!"
            redirect_to @user
        else
            flash[:alert] = "Account creation failed: #{@user.errors.full_messages.to_sentence}"
            render :new
        end

    end

    def show
        @user = User.find_by(id: params[:id])
    end

    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
        <%= render partial: "layouts/errors", locals: {object: @comment} %>
<div class ="row">
    <div id="comment-container">
        <h4>Edit Comment for <%= @comment.poem.title%></h4>

            <%= form_for(@comment) do |f|%>

              <div class="form-group">

                <%= f.label :content %>
                <%= f.hidden_field :poem_id %>
                <%= f.text_field :content %>
              </div>

              <%= f.submit "Edit Comment", class: "btn btn-warning" %>

            <% end %>
    </div>
</div>
<h4>Go back to poem:<%= link_to @comment.poem.title, poem_path(@comment.poem_id) %></h4>

app/views/comments/index.html.erb
<% if @poem %>
  <h3>Comments for <%= @poem.title%></h3>
<% else %>
  <h1>All Comments</h1>
<% end %>

<div>
<% @comments.each do |comment|%>
  <h4><strong><%= comment.user.name%></strong></h4>
  <p><em><%= comment.content%></em> <%= link_to comment.poem.title, poem_path(comment.poem_id) %></p>
    <% if comment.user == current_user %>
      
        <%= link_to "Edit", edit_poem_comment_path(comment.poem.id, comment.id), class: "btn btn-warning btn-xs"%>
        <br><br>
      
        <%= button_to "Delete", { action: "destroy", id: comment.id },
                                method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
    <% end %>
<% end %>
</div>

app/views/comments/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @comment} %>
<br> <br>
<% if @comment.poem %>
<h4>Add a Comment for <%= @comment.poem.title%></h4>
<% end %>


<%= form_for([@poem,@comment]) do |f|%>
      
   <%= f.label :content %>
   <%= f.hidden_field :poem_id %>
   <%= f.text_field :content %>

   <%= f.submit "Create Comment", class: "btn btn-primary"%>

<% end %>

<p><%= link_to "Go Back to the Poem", poem_path(@poem) %><p>

<p><%= link_to "Go back to Poems page", poems_path %>

app/views/comments/show.html.erb
<h2><%= @comment.content%> - <%= @comment.user.name%></h2>

<% if @comment.user == current_user %>
  <%#= link_to "Edit Comment", edit_comment_path(@comment), class: "btn btn-warning"%>
   <%= link_to "Edit Comment", edit_poem_comment_path(@comment.poem, @comment), class: "btn btn-warning"%>
  
<% end %>

<h4>Go back to poem:<%= link_to @comment.poem.title, poem_path(@comment.poem_id) %></h4>  

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoritePoems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
  </head>

  <body>
      
       <header class="navbar navbar-fixed-top navbar-light">
         <div class="container">
        
       <nav>
           <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                 <li> <%= link_to "Poems", poems_path %></li> 
                 <li> <%= link_to "Add a Poem", new_poem_path %> </li>
                  
                  <li><%= link_to user_path(current_user) do %>
                        <%= current_user.name %>'s Poems
                  <% end %> </li>
                  <li><%= link_to "Home", root_path %></li> 
                  <li><%= link_to user_path(current_user) do %>
                        Welcome <%= current_user.name %>
                  <% end %> </li>
                  <li><%= link_to "Logout", logout_path, method:"delete"%></li>

               <% else %>
                  
                 <li><%=link_to "Sign Up", signup_path %></li>
                  <li><%= link_to "Log In With Google", '/auth/google_oauth2'%> </li>
                  <li><%=link_to "Log In", login_path %></li>
              <% end %>
            </ul>
       </nav>
       </div>
       </header>
       <div class="center jumbotron">
           <h1>Favorite Poems</h1>
       </div>
       <div class="container">
      
           <% if flash[:notice] %>
              <div class="alert alert-success" role="alert">
                <%= flash[:notice] %>
              </div>  
           <% end %>
       
          <% if flash[:alert] %>
            <div class="alert alert-danger" role="alert">
            <%= flash[:alert] %>
            </div>
        <% end %>
        <div class="container">
           <%= yield %>
        </div>
    </div>
    
  </body>
</html>

app/views/poems/_form.html.erb
<div class="form-div">
  <!--<div class="col-md-6 col-md-offset-3">-->
    <%= form_for(@poem) do |f|%>
     <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :size=>"48" %>
     </div>
     <br><br>
     <div class="form-group">
        <%= f.label :content %>
        <br>
       
        <%= f.text_area :content, :cols => 50, :rows => 20 %>
      </div>
     <br><br>
     <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
    <% end %>
 <!-- </div>-->
</div>

app/views/poems/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @poem} %>
<h3>Edit <%= @poem.title%></h3>

<%= render partial: 'form' %>

<p class="poem-edit"><%= link_to "Go Back to the Poem", poem_path(@poem), class: "btn btn-warning" %><p>

app/views/poems/index.html.erb
    <h2>Poems</h2>
      <div>
      <% @poems.each do |poem| %>
        <div>
          <h4><%= link_to poem.title, poem_path(poem) %></h4>
        
        </div>
      <% end %>

 
     </div>

 
<%= form_tag '/search', method: 'get' do %>
    <%= label_tag :Poem_by_first_letter %>
    <%= text_field_tag :letter %>

    <%= submit_tag("Search") %>

<% end %>

app/views/poems/new.html.erb
<h3>Add a New Poem</h3>


<%= render partial: "layouts/errors", locals: {object: @poem} %>

<%= render partial: 'form' %>

app/views/poems/search.html.erb
<h4>Search Result</h4>
 
<div> 
  <% @results.each do |result| %>
          <p><%= link_to result.title, poem_path(result) %></p>
  <% end %>

  <p><%= link_to "Go back to Poems page", poems_path, class: "btn btn-success" %></p>
</div>

app/views/poems/show.html.erb
<h3><%=@poem.title%></h3>
<h4 class="poem-title">Poem Added By: <%=link_to @poem.user.name, user_path(@poem.user)%> </h4>

<div class="card poem-content" style="width: 34rem;">
   <div class="card-body">
     <%= @poem.content%>
   </div>

 
      <br><br>
      <% if @poem.user == current_user %>
      <%= link_to "Edit Poem", edit_poem_path(@poem), class: "btn btn-warning btn-sm" %> 
      <%= link_to "Delete Poem", @poem, method: :delete, data: { confirm: "Really?" }, class: "btn btn-danger btn-sm" %>
      <% end %>


<br><br>


    <div class="comments-content">

        <p><%= link_to 'Add a comment', new_poem_comment_path(@poem), class: "btn btn-success"%></p>
        <p><%= link_to 'Comments', poem_comments_path(@poem.id) %></p>
        <p><%= link_to "Go back to Poems page", poems_path %></p>
    </div>

</div>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @user} %>
<div class="row" >
  <<div class="form-container">
    <h3>Sign Up</h3>
    <%= form_for(@user, url:'/signup') do |f| %>
      <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
      </div>
      
      <div class="form-group">
          <%= f.label :email %><br>
          <%= f.email_field :email%>
      </div>

      <div class="form-group">
      
          <%= f.label :password %><br>
          <%= f.password_field :password %>
      </div>
      

      <%= f.submit "Submit", class: "btn btn-primary" %>

    <% end %>
    
    <br>
     <%= link_to "Log In With Google", '/auth/google_oauth2' , class: "btn btn-primary"%>
    </div>
</div>

app/views/users/show.html.erb
<h3>Added by <%=@user.name %></h3>
  <div class="container user-poem" >
    
    <% @user.poems.map do |poem| %>
       <h4> <%= link_to poem.title, poem_path(poem) %></h4>
    <% end %>
   </div>